### ISSUE TITLE
1.6 doesn't appear to work with Photoshop CS6

### ISSUE THREAD

**Issue by marlonrichert** [fikovnik/ShiftIt#102]
Keyboard shortcuts don't work, nor do the menu items. They seem to do _something_, but not what they're supposed to do.

Mac OS X 10.7.5

**Comment by RaphaelDDL** [comment]
Just an update about this issue:

MacBook Pro Yosemite 10.10.3 with Photoshop CC 2014. No luck. The window just jump around but it's size is not changed. Log is empty :/

**Comment by brunowego** [comment]
Do not work for me too.

OSX 10.11, ShiftIt 1.6.3 and Photoshop CC

Thanks!
