### ISSUE TITLE
Shiftit can't be started on OSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by ghost** [fikovnik/ShiftIt#136]
I know the OS is still in Beta, but you can't start Shiftit because there is no way (that I can find) to enable it in the Accessibility System Preferences

**Comment by tomasfejfar** [comment]
:+1: re-checking the checkbox worked :)

**Comment by Jaskarans1ngh** [comment]
how do i even install this on my mac, i downloaded the zip file but dont know what to do from there, please help. Thanks

**Comment by fikovnik** [comment]
@Jaskarans1ngh - you should get the zip from the [Releases](https://github.com/fikovnik/ShiftIt/releases). Then you simply unzip (double click in Finder) and drag and drop the resulting ShiftIt.app into you Application folder. Finally, open it by double clicking on it.

**Comment by ssgao** [comment]
uncheck, restart the system, and recheck worked for me
