### ISSUE TITLE
Shortcuts for 1/3 and 2/3 Sizes

### ISSUE THREAD

**Issue by greysonp** [fikovnik/ShiftIt#148]
Hi there! First off, I love the this app! Suuuper helpful.

One feature I wish it had though was the ability to resize windows to 1/3 and 2/3 sizes.  Or just the ability to add custom sizes and shortcuts in general.

Thanks!

**Comment by SodY2** [comment]
+1

**Comment by NimoTh** [comment]
+1

**Comment by mat128** [comment]
Any updates for this? :)

**Comment by greysonp** [comment]
Last commit to both master and develop branches was a year ago. And hey, can't blame the owner, maintaining OSS can be hard. However, I've since switched to [spectacle](https://github.com/eczarny/spectacle) which is still actively maintained. Their resizing feature goes in steps smaller than 1/2 :)

**Comment by cjcjameson** [comment]
Been merged! Can close. Looking forward to a new release with this feature.
