### ISSUE TITLE
Text showing up in Japanese

### ISSUE THREAD

**Issue by Gunga** [fikovnik/ShiftIt#166]
When I double click on the app, this keeps popping up:

![screen shot 2015-04-28 at 1 25 27 am](https://cloud.githubusercontent.com/assets/7865250/7365564/52a535b8-ed46-11e4-9e76-4f178abee974.png)

My laptop does not have Japanese set up anywhere as the default language and even when I *enable access for assistive devices* I keep getting that message.

OS X **10.8.5**
ShiftIt **1.6.3**

**Comment by fikovnik** [comment]
Another good one :(

That will be difficult for me to reproduce. My locale is set to English. If I switch to Japanese it works well. If I switch back to English, ShiftIt is back in English. The Japanese translation was added in 1.6.1. Perhaps what you could do is to just download the latest release manually or via homebrew cask (when it is merged).

**Comment by danmoore2205** [comment]
I'm also having the same problem

**Comment by fikovnik** [comment]
I merged in @Gunga 's patch. Thanks a lot for reporting and contributing.
