### ISSUE TITLE
'Authorization Required' screen even after enabling access for assistive devices

### ISSUE THREAD

**Issue by ckuehne** [fikovnik/ShiftIt#170]
ShiftIt (1.6.3) starts and tells me to enable the setting. When I do so and restart it again, it tells me again.

**Comment by Gunga** [comment]
I noticed this as part of the issue I opened (#166). Last night I opened a pull request ( https://github.com/fikovnik/ShiftIt/pull/169 ) with a fix. Are you on OS X 10.8.5 (Mountain Lion) ?

**Comment by ckuehne** [comment]
> Are you on OS X 10.8.5 (Mountain Lion) ?
Yep.

**Comment by fikovnik** [comment]
Merged @Gunga 's changes. Thanks a lot for reporting and contributing.

**Comment by cerker** [comment]
Just for the records: I had the same problem after upgrading to ShiftIt 1.6.3 on 10.9.5. The trick was to disable ShiftIt in the assitive devices list and then enable it again. 
This is explained here by @lookfirst: https://github.com/fikovnik/ShiftIt/issues/110#issuecomment-59555725

**Comment by haol615** [comment]
I'm on 10.10.5 and have the same problem, even after disabling and enabling ShiftIt in Accessibility. Is there any other workaround that I can try? Thanks!

**Comment by Gunga** [comment]
Hey @haol615, If you downloaded the latest release (1.6.3) it would still be happening because the changes I made were merged into **develop** branch but haven't been merged into _master_ yet. You can checkout that branch and build it yourself or wait for an official 1.6.4 to release.

**Comment by haol615** [comment]
Gotcha. Thanks, @Gunga ! I've downloaded 1.5 for now and I'll wait for 1.6.4.
