### ISSUE TITLE
I'm running a large 4K tv as a display 

### ISSUE THREAD

**Issue by haydonryan** [fikovnik/ShiftIt#178]
Would be great to have more options as to sizing.  

When working from home my screen is a 55" HDTV 4k TV. Therefore I can fit a lot more than left and right panels.  Would be really cool to see the use of mash+numpad to provide direct movement to a predefined grid (either 2x2 or 3x3).

mash+numpad-7 puts current window into the top left hand corner.

take care,
Haydon

ps Love Shiftit.

**Comment by ameyec** [comment]
See #231

**Comment by rca** [comment]
1.6.4 suppports sizing to 1/3.

Closing.
