### ISSUE TITLE
Enable shiftit without setting permissions?

### ISSUE THREAD

**Issue by realalexhomer** [fikovnik/ShiftIt#201]
Hi,
I just started a new job where there are pretty strict security measures in effect. I don't have access to security / privacy settings in system preferences and therefore can't use shiftit it seems. I am kind of addicted to using shiftit and am not looking forward to having to work / code without it.

I am curious if there are any possible workarounds or if this is just a limitation that can't be overcome? I would also really appreciate if anyone knows of any alternative solutions that might not need access to security & privacy settings? Is there any way I could build it myself and not need to adjust security settings?

If it matters I'm running Yosemite 10.10.5

Thanks!

**Comment by bornalexhomer** [comment]
If anyone could point me in the right direction I would also be willing to contribute

**Comment by fikovnik** [comment]
This might be difficult. One way would be to implement a new driver based on apple script. Either generate apple script on the fly [1] or the scripting bridge [1] (maybe it is very outdated technology).

Another alternative are the functions referenced from: http://freequartz.googlecode.com/svn/trunk/CoreGraphics/include/CoreGraphics/CoreGraphicsPrivate.h

[1] https://snipt.net/nick/applescript-to-move-and-resize-windows/
[2] https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ScriptingBridgeConcepts/Introduction/Introduction.html

**Comment by realalexhomer** [comment]
Hey,
Thanks for getting back to me. I actually managed to hack around it with this:

https://github.com/fikovnik/ShiftIt/issues/151
