### ISSUE TITLE
ShiftIt 1.6.3 doesn't work on ElCapitan 10.11.4 

### ISSUE THREAD

**Issue by skhattane** [fikovnik/ShiftIt#207]
The app doesn't launch correctly and hotkeys failed. The icon is not visible in system tray.
Someone have the same issue ?

**Comment by fikovnik** [comment]
I have not updated yet, but will check asap.

**Comment by skhattane** [comment]
After reinstall shiftit 1.6.3, it works. I don't know why the issue the first time.

**Comment by fikovnik** [comment]
I don't think you need to reinstall - you only need to give it back the permissions to use accessibility API. It should prompt for it. I just updated to 10.11.4 and it worked as expected.
