### ISSUE TITLE
Doesn't recognize that I already enabled Accessibility permissions

### ISSUE THREAD

**Issue by ecbrodie** [fikovnik/ShiftIt#210]
I have a MacOS 10.11.5 desktop and I downloaded ShiftIt through Homebrew last week.

After installing, I enabled Accessibility Permissions trough the Security --> Privacy tab in System Preferences. However, every time I do a ShiftIt command (ie, ctrl-cmd-M for maximize screen), I still get that popup prompt to set those permissions again. I have followed the instructions multiple times, even disabled and re-enabled it again, but that is still not making the popup go away on subsequent ShitIt commands. Something seems broken...

**Comment by fikovnik** [comment]
That will be tricky for me to debug. I would try to remove ShiftIt from the list of permitted apps in the system preferences and then to run it again.

You can recheck what is really in the system using the following:
```sh
sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "SELECT * FROM access"
```

which should show something like:
```sh
kTCCServiceAccessibility|org.shiftitapp.ShiftIt|0|1|1|
```

**Comment by ecbrodie** [comment]
Sorry, I'm going to close this issue. The problem was that I still had SizeUp installed and running on my computer. With SizeUp closed, there is no error message, as expected.
