### ISSUE TITLE
Shiftit Unresponsive In Multi-Monitor Scenario With Fullscreen Terminal (iTerm2)

### ISSUE THREAD

**Issue by mvxt** [fikovnik/ShiftIt#219]
I tried to look through already-open issues to find something similar but didn't. 

_**Summary**_
With a multi-screen setup (external monitors and built-in), if iTerm2  is used in fullscreen mode, Shiftit becomes unresponsive and stops working entirely.

_**System Info**_
macOS Sierra (10.12)
MacBook Pro (Retina, 15-inch, Mid 2015)
**Processor** 2.5 GHz Intel Core i7
**Memory** 16 GB 1600 MHz DDR3
**Graphics** Intel Iris Pro 1536 MB
 
_**Steps To Recreate**_

1. Use two external monitors (E1 & E2) as well as built-in screen (B). Align them like so: E1 E2 B
2. Make sure Shiftit is on, and open at least one window of any kind on all three screens (I had an Excel sheet open on E1, iTerm2 open on E2, and Google Chrome on B). However, most important is to make sure iTerm2 is open on E2. 
3. Make sure iTerm2 is not in fullscreen mode yet. Check Shiftit on all three monitors and ensure Shiftit is working.
4. Now put iTerm2 in fullscreen mode (Cmd + Return). Now check Shiftit on all windows, and observe that Shiftit no longer responds. Hotkeys/keyboard shortcuts don't work, and manually clicking the options from dropdown menu also doesn't work.
5. Exit out of fullscreen mode on iTerm2 (Cmd + Return) and observe Shiftit working again.

_**Caveats**_

1. On single-screen mode, both external and built-in, things work great. If I have iTerm2 on fullscreen mode, I do (Alt + Tab) to switch to another window and Shiftit still works great.
2. Unfortunately, I cannot remember if this was an issue in El Capitan. I only recently started using iTerm2 in fullscreen mode (always just used Shiftit maximize before, but I like the look of fullscreen better). 

Thanks for your time!

**Comment by fikovnik** [comment]
This is the same as #216.
