### ISSUE TITLE
Hot keys not working in some condition with OS Sierra 

### ISSUE THREAD

**Issue by stevenshim** [fikovnik/ShiftIt#221]
After I updated mac OS to Sierra, hot keys doesn't work in some condition.

I use multi monitor. 
When I enter any application into full screen on one side, hot keys doesn't work on any application which is not in full screen on other side monitor.
It was ok with older version of Mac OS.

Thanks

**Comment by fikovnik** [comment]
Looks like #216  - please try the beta version 1.6.4 downloadable form github.

**Comment by stevenshim** [comment]
it works like a charm :)
