### ISSUE TITLE
Not working with two monitors if one has a full screen app

### ISSUE THREAD

**Issue by cvanderwall14** [fikovnik/ShiftIt#222]
ShiftIt is failing with two monitors if an application is maximized one of the screens. For example, I usually have Chrome and Emacs open on my large external monitor and switch between Slack and Spotify (both maximized) on my Macbook Air's screen. None of the ShiftIt commands work on the apps showing in my external monitor if Slack is maximized and displayed on my laptop screen. If I switch to a different desktop on my laptop screen the ShiftIt commands start working again.

**Comment by fikovnik** [comment]
Please check the latest beta available in releases. This is the same as in #216

**Comment by wav** [comment]
FYI: I was experiencing the same with 1.6.3. I tried the 1.6.4 beta today it works as expected now.

**Comment by fikovnik** [comment]
@cvanderwall14 - does the 1.6.4 works for you?

**Comment by cvanderwall14** [comment]
1.6.4 fixes this issue for me, thanks!
