### ISSUE TITLE
Feature request: top top left

### ISSUE THREAD

**Issue by TylerBarnes** [fikovnik/ShiftIt#225]
It would be useful for large screens to be divided into 16 instead of 4. On a large imac each quarter of the screen is nearly the size of a macbook screen.

This could be implemented by allowing two commands to be pressed one after the other where the second command cascades into the bounds of the first.
ie the command to move the window to the top left could be pressed and the window would move but if quickly pressed again it would move to the top left quarter within the top left quarter of the screen.

I know nothing about mac development or how difficult this would be but it would be an incredibly useful feature.

**Comment by ameyec** [comment]
Working on a Ultra Wide monitor, I have a similar request, maybe 9 zones is also a possibility?

**Comment by cjcjameson** [comment]
Much like https://github.com/fikovnik/ShiftIt/commit/4eb812c6f85a76742e43a1b88ab68d5a4d1e7bfe there is probably a commit you can pull from @onsi's fork -- or maybe that commit has the effect you're looking for? I'm not reading the code too closely. See #223 for where it was merged.
