### ISSUE TITLE
Divide Screen into Thirds

### ISSUE THREAD

**Issue by bmwillrath** [fikovnik/ShiftIt#231]
I've just moved to a 34" Curved Display, and using my left and right keys works great but they are way to wide, Would really love to be able to divide a screen this size into 3rd's so I can snap it to 1/3 2/3 or 3/3 to keep it functional.

**Comment by VMelandri** [comment]
Same here, I have a 4k 28 inches, I would love to be able to do 3rds. I've seen commits are in master for this feature already, when are we gonna get a release for it? :)

**Comment by ameyec** [comment]
Seems also related to #122 not sure why any of this is not visible in the current version or settings ...

**Comment by cjcjameson** [comment]
#223 resolved this -- just waiting for a new release (and hopefully an update to the brew cask?) !

**Comment by rca** [comment]
This is addressed in 1.6.4; hitting the same direction multiple times cycles 1/2, 1/3, 2/3 sizes.  However, keep an eye on #254 for updates to this behavior.
