### ISSUE TITLE
Multi Monitor Support

### ISSUE THREAD

**Issue by daxaxelrod** [fikovnik/ShiftIt#235]
First let me say that ShiftIt is absolutely incredible and makes my laptop so much more productive!

That being said, It only seems to work for one monitor at a time even when I have a second plugged in. Are there any multi-monitor support talks going on?

Again thank you and have an awesome day! :)

**Comment by fikovnik** [comment]
Thanks for kind words!

I use it with multiple screens, what exactly are you missing?

**Comment by daxaxelrod** [comment]
When I have a second monitor linked by mini display port to hdmi to my macbook, the commands can only be used in each specific window. I cannot move an application from one screen to another without a manual drag.

Keep being awesome!

**Comment by VMelandri** [comment]
Works fine for me.
A different but maybe related issue I'm having is that it does not work if any window is in fullscreen mode. So i never use fullscreen and I use maximize with shiftit, instead.

**Comment by jackcogdill** [comment]
I have used ShiftIt for a while and love it.

However, I now use a triple monitor setup and experience some issues. A lot of times it will stop working even after restarting the app (I suspect the issue is with multiple monitors).
Essentially all of the keyboard shortcuts stop working.

**Comment by fikovnik** [comment]
Hi,

Have you tried the latest beta available from releases here on github?

/cheers
Filip

**Comment by jackcogdill** [comment]
@fikovnik Hey, I tried using the newest beta release and it seems to have fixed most of the issues! Thank you
Jack

**Comment by fikovnik** [comment]
Glad to hear that.
