### ISSUE TITLE
Shortcuts for red, orange and green buttons

### ISSUE THREAD

**Issue by lamortenera** [fikovnik/ShiftIt#236]
Hi, thanks for implementing this wonderful tool, I love it. 
This is not really an issue that I am going to raise, it's more a curiosity question. 
ShiftIt offers many options, and that's great. But would it be possible to have some shortcuts that emulate EXACTLY what the red, orange and green buttons do, and nothing else? I could help out with coding, if you could give me a hint about how to do that (I am new to mac and objective c, but I can pick it up).

Cheers
Alessandro

**Comment by fikovnik** [comment]
Hi,

I think you can "emulate" it pretty well:

```
red -- cmd-q
yellow -- cmd-m
green -- toggle zoom
option + green -- maximize
```

**Comment by lamortenera** [comment]
thanks a lot. I also discovered that many applications support the fullscreen shortcut ctrl + cmd + F. Sorry for the stupid question and thanks for the answer, feel free to close the issue.

Cheers
Alessandro
