### ISSUE TITLE
shiftit crashes when trying to change position of Python figure

### ISSUE THREAD

**Issue by thoyo** [fikovnik/ShiftIt#238]
If I open a python figure like this:

```
$ python
>>> import matplotlib.pyplot as plt
>>> plt.figure()
>>> plt.show()
```

And then try to shift it to some part of my display with shiftit, it doesn't work, shiftit crashes and disappears from the menu bar. Shiftit seems to work fine for the other applications.

Shiftit version: 1.6.3
MAC OS X version: el Capitan 10.11.6

**Comment by fikovnik** [comment]
I just tried that and it works fine. I use the 1.6.4 beta on OSX sierra.

**Comment by thoyo** [comment]
Solved it, the problem was not shiftit, but the way I was opening the python figure. I was using 

`>>> plt.pause(1)`

Instead of `show()`
