### ISSUE TITLE
ShiftIt Imposter App - Magnet

### ISSUE THREAD

**Issue by DaveyJake** [fikovnik/ShiftIt#242]
As a long time user of ShiftIt (for the last 7 years) I was shocked when I found an app called Magnet that (essentially) promotes is itself as a carbon copy of ShiftIt with subtle--SUBTLE--changes to their UI.

@fikovnik Not sure if you signed off on it or were involved in its development but if you were I feel that you deserve SOME credit for it.

[Magnet Window Manager](https://itunes.apple.com/us/app/magnet/id441258766?mt=12)

**Comment by fikovnik** [comment]
Hi,

Thanks for using ShiftIt!!! - this is the best credit ever!

I do not know if they used Shiftit in any way for building it, but anyway, people have choice to buy something or use this free software :-)

/cheers
Filip
