### ISSUE TITLE
Ship a release?

### ISSUE THREAD

**Issue by cjcjameson** [fikovnik/ShiftIt#246]
Hi @fikovnik, I hope you're doing well! There are some commits on Master and from the 1.6.4-Beta that have been there for a while but aren't available for general usage (i.e. brew install).

Can you please consider shipping a new non-beta release? If a release ships with the content from https://github.com/fikovnik/ShiftIt/pull/223 then I'd eagerly recommend to many other people and Onsi himself that the Onsi fork be formally closed down.

Thanks!

**Comment by rca** [comment]
Hey there, I wanted to check out the merged feature too.  I created a release on my fork if you're interested: https://github.com/rca/ShiftIt/releases/tag/rca-master

@cjcjameson

**Comment by fikovnik** [comment]
There is the beta release which should me made into a final one. If you
want to make it, I'll happily add you to the repository :-)

**Comment by cjcjameson** [comment]
Just to clarify, @rca 's build is 7 commits beyond the 1.6.4-beta, but it's got what I'm referring to. Gotta take it for a spin this weekend or next week!

**Comment by rca** [comment]
@fikovnik can you give me some more info on the make-a-final-release process?  I'd be happy to help out if I can.

**Comment by fikovnik** [comment]
That would be great!

The fabric script ran with 'release' task should do the most of the things.
Additionally the 1.6.4 milestone should be closed and the Brew cask updated
to fetch three latest release from GitHub

**Comment by rca** [comment]
I took a bit of time to attempt a release myself.  When running `fab release` I get this error: 

```
[berto@g6]$ fab release
[localhost] local: defaults read /Users/berto/Projects/ShiftIt/ShiftIt/ShiftIt-Info.plist CFBundleVersion
[localhost] local: git diff-index --quiet HEAD --
Warning: there are pending changes in the repository. Run git status
Traceback (most recent call last):
  File "/Users/berto/.virtualenvs/shiftit/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/Users/berto/.virtualenvs/shiftit/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/berto/.virtualenvs/shiftit/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/berto/Projects/ShiftIt/fabfile.py", line 246, in release
    milestone = _get_milestone()
  File "/Users/berto/Projects/ShiftIt/fabfile.py", line 95, in _get_milestone
    raise Exception('Unable to find milestone: %s' % proj_version)
Exception: Unable to find milestone: 1.6.3
```

I'm opening up a PR with a few tweaks I made to get a build / release environment setup locally.

**Comment by rca** [comment]
@fikovnik any feedback on this

**Comment by fikovnik** [comment]
Sorry, I was away for past three weeks. The release script expects to to find a milestone. What should be done is to increase the version number to 1.6.4. Then the script will be able to find the milestone in https://github.com/fikovnik/ShiftIt/milestones and do the rest of its task.

**Comment by rca** [comment]
1.6.4 has been released; closing.
