### ISSUE TITLE
ShiftIt not working on Sierra High

### ISSUE THREAD

**Issue by lyager** [fikovnik/ShiftIt#253]
I upgrade to Sierra High and noted that my ShiftIt installed from Brew version 1.6.3 was not working anymore. The menuicon was there, but clicking on 'left', 'right' etc didn't do anything at all. Another issue mentioned that 1.6.4 might work. I cloned, compiled, but the 1.6.4 version doesn't show up in Accessibility preferences at all, and now I'm stuck...

I think Sierra High has changed some thing when it comes to accessibility, because my old Alfred version stopped being able to lock my screen after the Sierra High upgrade as well.

**Comment by fikovnik** [comment]
I heard that something has changed. I'm waiting for a new laptop - the old one does not run the latest OSX. Once I get it (though it is a university purchase so it might take a while) I will have a look into it.

**Comment by NimoTh** [comment]
Hi, I just upgraded to High Sierra (10.13) and installed Shiftit for the first time on my personal Mac. Left, right, maximize with out-of-the-box configuration work just fine. (I have been using it for a while on my work Mac with Sierra (< 10.13).)

**Comment by lyager** [comment]
I just tried version 1.6.3 again.. I got the pop-up requesting access through accessibility, and ShiftIt was there (which it wasn't before). After granting permissions and hitting 'Recheck' ShiftIt 1.6.3 now works. I'll see if it still works after a reboot too.

**Comment by lyager** [comment]
There definitely something odd about this. Now it has stopped working again, and restarting the app doesn't help. I'm unable to find anything in the logs really. If there is some tests I can run, please let me know.

**Comment by rca** [comment]
I upgraded to High Sierra and it works fine for me. Strange indeed.

**Comment by rca** [comment]
Please try the new 1.6.4 release to see if the problem persists.

**Comment by lyager** [comment]
This seems to resolve the problem - however I have only tested it for a few minuttes. I can reopen if the problem comes back.. Thanks!

**Comment by mpower02** [comment]
I'm running High Sierra and just updated to ShiftIt 1.6.4 today.  I'm having issue with the shortcut keys for repositioning windows. Ctr+Opt+Command + arrow key will reposition the window but not to the default correct size.

Before this version upgrade, I would just need to press the shortcut keys once and it will reposition half the screen (top, right, left or bottom).  Now pressing shortcut key will give me 3 sizes, you keep on having to press on shortcut keys until the window resize to the size you want (for me it's usually half the screen size).  Does anyone know the settings to change this?

**Comment by rca** [comment]
hi @mpower02.  I know exactly what you're talking about.  This is a new feature that was merged into master earlier this year.  Please take a look at PR #223 for details.

Essentially, if you resize in the same direction multiple times you can toggle between 1/2 2/3 and 1/3 of the screen.  It took some getting used to, and I'm not quite sure I'm in love with it myself, but I am starting to like it a little.  Not too much.  ;)  I think it makes most sense on very wide screens where there are a lot of pixels.

**Comment by mpower02** [comment]
Thanks for clarifying @rca, I wish there was a setting to turn off this feature.  I've been trying to get used to this for about a day now and honestly not a big fan of it. :(  I connect my laptop to the Thunderbolt Display and prefer the old method.  What used to be a one-time shortcut key is now like fumbling around 3x to get the expected screen size.  Will need to reinstall an older version now.

**Comment by rca** [comment]
@mpower02 this is good feedback; do you mind opening up an issue, please.

**Comment by fikovnik** [comment]
Perhaps, it would make sense if at first it does 1/2 and then 1/3 and 2/3?

**Comment by rca** [comment]
Here's the part that I personally find counter-intuitive about the way it currently works:  shift a window right, to left, to right, to left, to right, etc.  i would assume consistent resizing to half the window.  Instead it alternates between 1/3, 1/2, 2/3 sizes.

I don't mind too much that hitting _the same direction_ alternates between sizes, but going from one direction to another should always be consistent: half the screen.

**Comment by egold** [comment]
I've been using ShiftIt for about 4 years, and also am lately having issues. If anyone is looking for an alternative, Spectacle does what ShiftIt did for me for years, but seems to have fewer issues on later versions of macOS -- https://www.spectacleapp.com/
