### ISSUE TITLE
App windows change in size

### ISSUE THREAD

**Issue by MichaelA59** [fikovnik/ShiftIt#261]
So I created 2 hotkeys for `left` & `right`. CMD+Shift+G or V will do the trick.

The issue is, I want it to be the full left side or full right side, but when I hit the hot key it varies between three sizes, super small, full left/right side and then like 3/4 of the page. What gives?

**Comment by fikovnik** [comment]
Please have a look at https://github.com/fikovnik/ShiftIt/issues/254.

**Comment by fikovnik** [comment]
Duplicate if https://github.com/fikovnik/ShiftIt/issues/254

**Comment by MichaelA59** [comment]
Thanks guys!
