### ISSUE TITLE
Sign released binary

### ISSUE THREAD

**Issue by kenchan0130** [fikovnik/ShiftIt#264]
Please kindly sign released binary.

It seems that ShiftIt app has no missing sign (I used https://github.com/fikovnik/ShiftIt/releases/download/version-1.6.4/ShiftIt-1.6.4.zip).
Because of this, I cannot install it  by Gatekeeper to my machine due to the firm's security policy.

**Comment by rca** [comment]
Is 1.6.3's signature recognized?  Can you try 1.6.5 that I just released and see if that works.

@fikovnik perhaps this has something to do with my release environment?

**Comment by fikovnik** [comment]
@kenchan0130 - were you able to use the previous versions of genthat?

**Comment by kenchan0130** [comment]
@fikovnik 

I have tried again with 1.6.3, 1.6.4 and 1.6.5 of shitit app.
In all of these versions, the popup has appeared.

![popup_1 6 5](https://user-images.githubusercontent.com/1155067/35954731-b788843a-0cce-11e8-8507-28e45c0c9bca.png)

**Comment by fikovnik** [comment]
I'm sorry to disappoint you, but AFAIK to have the app signed we would need to become part of Apple's Developer Program for $99 per year. I don't have $99 to spare on that and honestly even if I had I would prefer to donate it to a charity instead.
Can you install things using [homebrew cask](https://caskroom.github.io/)?

btw: this is just my personal view of this affair - others might disagree.

**Comment by rca** [comment]
@kenchan0130 there is a trick to this.  If you `ctrl+click` / "two-finger click" / "right click" on a package and then click Open; you'll be given an option to install anyway.

![image](https://user-images.githubusercontent.com/53537/35975594-40b21d3a-0cab-11e8-92c2-904362866a2f.png)

Unless we find someone to sponsor the Developer Program for ShiftIt; this issue is done.

Closing, and please re-open if and when things change.

**Comment by kenchan0130** [comment]
@fikovnik 

I understood the situation you are in.

@rca 

Thank you for your response.

> If you ctrl+click / "two-finger click" / "right click" on a package and then click Open; you'll be given an option to install anyway.

I cannot use these methods because the profile has been applied to my laptop such as:

![mac_profile_policy](https://user-images.githubusercontent.com/1155067/36013847-ebe5cca2-0da9-11e8-9e8e-81d6478d986d.png)

**Comment by rca** [comment]
This is a bummer.  I'm going to do some research and see if there's a way to get this thing signed.
