### ISSUE TITLE
Release note keep spinning never ending

### ISSUE THREAD

**Issue by elcolie** [fikovnik/ShiftIt#265]
![image](https://user-images.githubusercontent.com/18206728/35930273-11bb5db2-0c64-11e8-8685-b465f41cc51c.png)

![image](https://user-images.githubusercontent.com/18206728/35930374-4f00a48e-0c64-11e8-958c-3ffc457081c5.png)

Do you intended to keep it spinning?
Also I can not install the update

OSX: `10.13.3`

**Comment by mlo1088** [comment]
I tried to install the 1.6.5 release but when I try to unzip, it says the file is corrupt. Is this related?

https://github.com/fikovnik/ShiftIt/releases/download/1.6.5/ShiftIt-1.6.5.zip

**Comment by xiongchiamiov** [comment]
I don't see any mention of changes here in these issues, but this morning I got a prompt to update to 1.6.6, and it worked. 😄 So I think this is fixed.

**Comment by behnam** [comment]
Looks like it's fixed in #273. Version 1.6.5 can download and install the new version, 1.6.6, automatically.

**Comment by elcolie** [comment]
Seems like `1.6.4` need to be uninstalled
<img width="591" alt="image" src="https://user-images.githubusercontent.com/18206728/36884985-c3dc574e-1e16-11e8-86ad-cbba7fe3f228.png">
