### ISSUE TITLE
1.6.5 showing as 1.6.4

### ISSUE THREAD

**Issue by brianmorton** [fikovnik/ShiftIt#268]
just downloaded the release from the releases page:

![image](https://user-images.githubusercontent.com/1434096/36047242-50f1163e-0d90-11e8-88bd-d8e68c9460bd.png)

Edit: not sure if this means the 1.6.5 release is actually 1.6.4 and the wrong app was packaged, or if the version number just wasn't bumped

**Comment by brianmorton** [comment]
Update, within the app it is showing up as 1.6.5:

![image](https://user-images.githubusercontent.com/1434096/36047335-a62973f8-0d90-11e8-9c10-0fefe126a5cf.png)

**Comment by RogerMcCarty** [comment]
Check for updates looks a bit odd as a result ...

<img width="490" alt="screen shot 2018-02-11 at 1 24 28 pm" src="https://user-images.githubusercontent.com/7970363/36078711-1b684c58-0f2f-11e8-9a52-bd772230de1e.png">

**Comment by dulgan** [comment]
I think the 1.6.4 binary is in the zip, because the 1.6.5 fix on 1/3 - 2/3 - 1/2 cycle is not included...

**Comment by rca** [comment]
This should be fixed already; I'm currently working on a 1.6.6 release which should definitely fix this.
