### ISSUE TITLE
Empty Release Notes and Update Error!

### ISSUE THREAD

**Issue by behnam** [fikovnik/ShiftIt#269]
Version: 1.6.4

It's been a few days that I get the update notification, but the Release Notes don't load.
<img width="698" alt="screen shot 2018-02-12 at 8 31 26 am" src="https://user-images.githubusercontent.com/37169/36107533-4000c388-0fcf-11e8-8464-9ddc7616da7e.png">

And then when pressing Install Update button, get an Update Error message.
<img width="532" alt="screen shot 2018-02-12 at 8 31 30 am" src="https://user-images.githubusercontent.com/37169/36107575-55c428f4-0fcf-11e8-9c68-7174f52d6584.png">

The same happens when I click on "Check For Updates Now" from Preferences window.

I doubt that the problem is on my side, as it consistently repros at home and work.

I'm going to download the latest binary and install it manually, but reporting it here FYI.

**Comment by Neejoh** [comment]
Same here. Checked the system log and apparently the URL isn't correct;

    Feb 12 08:27:03 imac-rtv ShiftIt[565]: Sparkle Error: An error occurred while downloading the update. Please try again later.
    Feb 12 08:27:03 imac-rtv ShiftIt[565]: Sparkle Error (continued): The requested URL was not found on this server.

**Comment by saiqulhaq** [comment]
+1

**Comment by robungar** [comment]
Same issue

**Comment by thedashboardofmycar** [comment]
Same here

**Comment by eddified** [comment]
I experienced this issue as well.

**Comment by behnam** [comment]
Just a reminder for everyone here: you can set a 👍 on the original report to show that you're experience the problem, too. And click on Subscribe on the sidebar, if you like. This would keep the noise down for developers and others subscribed to the issue, while providing the information needed to the developers.

**Comment by xiongchiamiov** [comment]
Fyi this is a dupe of #265, although I think this one got more attention.

#267 is a pull to fix it, but it appears to be stuck in a "well, how do we test this?" spot.

**Comment by behnam** [comment]
Looks like it's fixed in #273. Version 1.6.5 can download and install the new version, 1.6.6, automatically.

Closing as a duplicate.
