### ISSUE TITLE
After updating to macOS Ventura, ShiftIt doesn't work any more..

### ISSUE THREAD

**Issue by kay-adamof** [fikovnik/ShiftIt#331]
Can everyone use ShiftIt yet after macOS Ventura?

**Comment by OldRustyDijkstra** [comment]
Yeah it's not working for me as well

**Comment by kay-adamof** [comment]
I noticed this issue fixed just now (2022/10/30 9:30)
@OldRustyDijkstra 
Thanks for responding me.

**Comment by kay-adamof** [comment]
Hmm, suddenly `shiftit` is no longer available again(2022/11/10 13:02）

**Comment by kay-adamof** [comment]
Sorry, it started working again.
