### ISSUE TITLE
Report: crashes frequently on Ventura 13.2

### ISSUE THREAD

**Issue by matoruru** [fikovnik/ShiftIt#334]
I'm not sure if the development is still on going (it doesn't seem so based on the git history). So I will share my workaround for restarting the app for the frequent crash.

```
pkill -KILL -f ShiftIt && open /Applications/ShiftIt.app
```

**Comment by matoruru** [comment]
By the way, thank you for providing the great app! I'm using every day and can't think of my life without this app 😀

**Comment by eduardoroliveira** [comment]
Try restarting your Mac. It solved my problem!

**Comment by matoruru** [comment]
Umm it didn't work for mine 😦

**Comment by matoruru** [comment]
But I realized that this crashing issue happens on having a call or meeting from Microsoft Teams.
